### ISSUE TITLE
Missing './vendor/' scss files

### ISSUE THREAD

**Issue by tomdohnal** [ctf0/Laravel-Media-Manager#23]
When I run `yarn watch` I got this error while compiling:

```
ERROR in ./resources/assets/vendor/MediaManager/sass/media.scss
Module build failed: ModuleBuildError: Module build failed: 
@import './vendor/animate';
^
      File to import not found or unreadable: ./vendor/animate.
Parent style sheet: stdin
      in /home/tom/Code/laravel/vue-media-manager/resources/assets/vendor/MediaManager/sass/media.scss (line 22, column 1)
    at runLoaders (/home/tom/Code/laravel/vue-media-manager/node_modules/webpack/lib/NormalModule.js:195:19)
    at /home/tom/Code/laravel/vue-media-manager/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/tom/Code/laravel/vue-media-manager/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/tom/Code/laravel/vue-media-manager/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/home/tom/Code/laravel/vue-media-manager/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/home/tom/Code/laravel/vue-media-manager/node_modules/async/dist/async.js:2257:31)
    at Object.callback (/home/tom/Code/laravel/vue-media-manager/node_modules/async/dist/async.js:958:16)
    at options.error (/home/tom/Code/laravel/vue-media-manager/node_modules/node-sass/lib/index.js:294:32)
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss ./resources/assets/vendor/MediaManager/sass/media.scss

ERROR in ./resources/assets/vendor/MediaManager/sass/media.scss
Module build failed: ModuleBuildError: Module build failed: 
@import './vendor/animate';
^
      File to import not found or unreadable: ./vendor/animate.
Parent style sheet: stdin
      in /home/tom/Code/laravel/vue-media-manager/resources/assets/vendor/MediaManager/sass/media.scss (line 22, column 1)
    at runLoaders (/home/tom/Code/laravel/vue-media-manager/node_modules/webpack/lib/NormalModule.js:195:19)
    at /home/tom/Code/laravel/vue-media-manager/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/tom/Code/laravel/vue-media-manager/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/tom/Code/laravel/vue-media-manager/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/home/tom/Code/laravel/vue-media-manager/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/home/tom/Code/laravel/vue-media-manager/node_modules/async/dist/async.js:2257:31)
    at Object.callback (/home/tom/Code/laravel/vue-media-manager/node_modules/async/dist/async.js:958:16)
    at options.error (/home/tom/Code/laravel/vue-media-manager/node_modules/node-sass/lib/index.js:294:32)
 @ ./resources/assets/vendor/MediaManager/sass/media.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss ./resources/assets/vendor/MediaManager/sass/media.scss
```

When I looked inside the `media.scss` file which is the file where the error is coming from, I noticed that it has the following imports:
```
@import './vendor/animate';
@import './vendor/progress';
@import './vendor/switcher';
@import './manager';
```
the `@import './manager';` is no problem, however, the remaining three imports point to `vendor` folder which was not created while running `php artisan vendor:publish provider="ctf0\MediaManager\MediaManagerServiceProvider"`. And it is not even in the source folder of this repository. 

Maybe I'm missing the point somewhere. I'll be very grateful for any piece of advice!

**Comment by ctf0** [comment]
sorry for that, plz update to the latest release
